In [427]:
#8-05-2024
# NUMPY=NUMPY MEANS NUMERICAL PYTHON.NUMPY IS A PYTHON LIBRARY.NUMPY IS A MATHEMATICAL FUNCTION.
# ARRAY IS A SINGLE TYPE DATA.LIST IS DYNAMIC.ARRAY IS STATIC.ARRAY IS INMUTABLE.LIST IS MUTABLE.
import numpy as np

In [428]:
s=np.array([4,5,6,7,1,2,3,9,3,7,8,9])
s

array([4, 5, 6, 7, 1, 2, 3, 9, 3, 7, 8, 9])

In [429]:
type(s)

numpy.ndarray

In [430]:
s.ndim

1

In [431]:
np.sort(s)

array([1, 2, 3, 3, 4, 5, 6, 7, 7, 8, 9, 9])

In [432]:
np.sum(s)

64

In [433]:
np.max(s)

9

In [434]:
np.min(s)

1

In [435]:
# MEAN[SAARE KO ADD PHIR DIVISION] , MEDIAN[ONLY CENTRAL VALUE GIVEN] , MODE[REPEATED VALUE] (imp):
#MEAN(AVERAGE):TOTAL SUM OF ALL VALUES DIVIDED BY THE NUMBER OF VALUES.ISSE DATA KA CENTRAL TENDENCY MEASURE KIYA JATA HAI.
#MEDIAN(MIDDLE VALUE):MEDIAN WO VALUE HOTI HAI JO DATASET KO ARRANGE KRNE PR EXACT CENTER ME AATI HAI.
#MODE(REPEATED VALUE):MODE WO VALUE HOTI HAI JO DATASET ME SBSE JYDA BAR ATI HAI.

In [436]:
np.median(s)

5.5

In [437]:
np.mean(s)

5.333333333333333

In [438]:
np.sqrt(s)

array([2.        , 2.23606798, 2.44948974, 2.64575131, 1.        ,
       1.41421356, 1.73205081, 3.        , 1.73205081, 2.64575131,
       2.82842712, 3.        ])

In [439]:
np.cbrt(s)

array([1.58740105, 1.70997595, 1.81712059, 1.91293118, 1.        ,
       1.25992105, 1.44224957, 2.08008382, 1.44224957, 1.91293118,
       2.        , 2.08008382])

In [440]:
s

array([4, 5, 6, 7, 1, 2, 3, 9, 3, 7, 8, 9])

In [441]:
s[2:6]

array([6, 7, 1, 2])

In [442]:
s[::-1]

array([9, 8, 7, 3, 9, 3, 2, 1, 7, 6, 5, 4])

In [443]:
s

array([4, 5, 6, 7, 1, 2, 3, 9, 3, 7, 8, 9])

In [444]:
np.insert(s,3,66)

array([ 4,  5,  6, 66,  7,  1,  2,  3,  9,  3,  7,  8,  9])

In [445]:
s

array([4, 5, 6, 7, 1, 2, 3, 9, 3, 7, 8, 9])

In [446]:
np.where(s==6)

(array([2], dtype=int64),)

In [447]:
np.where(s==7)

(array([3, 9], dtype=int64),)

In [448]:
s

array([4, 5, 6, 7, 1, 2, 3, 9, 3, 7, 8, 9])

In [449]:
#any=ANY MEANS koi ek value bhi agar true/false hui to wo true/false show krega
#all=saari value true/false  honi chahie usi ke according wo uska output deta hai


In [450]:
np.all(s>8)

False

In [451]:
np.all(s>0)

True

In [452]:
np.any(s>8)

True

In [453]:
np.any(s>25)

False

In [454]:
s

array([4, 5, 6, 7, 1, 2, 3, 9, 3, 7, 8, 9])

In [455]:
#VARIANCE(VAR):VARIANCE EK STATISTICAL CONCEPT HAI JO DATA POINTS KE BICH KI DISPERSION(ISKA MTLB HOTA HAI KI DATA POINTS KITNI 
# ALAG ALAG YA KITNI DUR HAI EK DUSRE SE)KO MEASURE KRTA HAI.KAM VARIANCE KA MTLB HAI KI DATA POINTS EK DUSRE KE BHUT KARIB HAI AUR JYDA VARIANCE KA
#MTLB HAI KI  DATA POINTS EK DUSRE SE  KAAFI DUR HAI.

np.var(s)

6.888888888888888

In [456]:
y=[1,1,1,1,1,1,1,1,1,1,1]
y

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [457]:
np.var(y)

0.0

In [458]:
s

array([4, 5, 6, 7, 1, 2, 3, 9, 3, 7, 8, 9])

In [459]:
print(s[-1])

9


In [460]:
s

array([4, 5, 6, 7, 1, 2, 3, 9, 3, 7, 8, 9])

In [461]:
len(s)

12

In [462]:
s.ndim

1

In [463]:
print(s[2])

6


In [464]:
g=np.reshape(s,(3,4))
g

array([[4, 5, 6, 7],
       [1, 2, 3, 9],
       [3, 7, 8, 9]])

In [465]:
g.ndim

2

In [466]:
g.shape

(3, 4)

In [467]:
g

array([[4, 5, 6, 7],
       [1, 2, 3, 9],
       [3, 7, 8, 9]])

In [468]:
#FLATTEN=FLATTEN EK METHOD HOTA HAI JO 2D ARRAY KO MULTIARRAY ME CONVERT KRTA HAI

In [469]:
g.flatten()

array([4, 5, 6, 7, 1, 2, 3, 9, 3, 7, 8, 9])

In [470]:
g

array([[4, 5, 6, 7],
       [1, 2, 3, 9],
       [3, 7, 8, 9]])

In [471]:
np.sum(g)

64

In [472]:
np.max(g)

9

In [473]:
np.min(g)

1

In [474]:
g

array([[4, 5, 6, 7],
       [1, 2, 3, 9],
       [3, 7, 8, 9]])

In [475]:
# T=TRANSPOSE OF MATRIX.MEANS JO ROW HAI USKO COLUMN ME AUR JO COLUMN HAI USKO ROW ME CONVERT KRTA HAI

In [476]:
g.T

array([[4, 1, 3],
       [5, 2, 7],
       [6, 3, 8],
       [7, 9, 9]])

In [477]:
g

array([[4, 5, 6, 7],
       [1, 2, 3, 9],
       [3, 7, 8, 9]])

In [478]:
t=np.array([[4,5,6],[2,3,4],[1,9,5]])
t

array([[4, 5, 6],
       [2, 3, 4],
       [1, 9, 5]])

In [479]:
t2=np.array([[4,5,6],[2,3,1],[3,3,1]])
t2

array([[4, 5, 6],
       [2, 3, 1],
       [3, 3, 1]])

In [480]:
t

array([[4, 5, 6],
       [2, 3, 4],
       [1, 9, 5]])

In [481]:
t2

array([[4, 5, 6],
       [2, 3, 1],
       [3, 3, 1]])

In [482]:
t+t2

array([[ 8, 10, 12],
       [ 4,  6,  5],
       [ 4, 12,  6]])

In [483]:
t-t2

array([[ 0,  0,  0],
       [ 0,  0,  3],
       [-2,  6,  4]])

In [484]:
t/t2

array([[1.        , 1.        , 1.        ],
       [1.        , 1.        , 4.        ],
       [0.33333333, 3.        , 5.        ]])

In [485]:
t.shape

(3, 3)

In [486]:
t2.shape

(3, 3)

In [487]:
t+t2

array([[ 8, 10, 12],
       [ 4,  6,  5],
       [ 4, 12,  6]])

In [488]:
t3=np.array([[5,6,7],[1,2,3]])
t3

array([[5, 6, 7],
       [1, 2, 3]])

In [489]:
t

array([[4, 5, 6],
       [2, 3, 4],
       [1, 9, 5]])

In [490]:
t2

array([[4, 5, 6],
       [2, 3, 1],
       [3, 3, 1]])

In [491]:
np.add(t,t2)

array([[ 8, 10, 12],
       [ 4,  6,  5],
       [ 4, 12,  6]])

In [492]:
np.subtract(t,t2)

array([[ 0,  0,  0],
       [ 0,  0,  3],
       [-2,  6,  4]])

In [493]:
t

array([[4, 5, 6],
       [2, 3, 4],
       [1, 9, 5]])

In [494]:
#dot=DOT MEANS FACTOR MULTIPLICATION.

In [495]:
np.dot(t,t2)

array([[44, 53, 35],
       [26, 31, 19],
       [37, 47, 20]])

In [496]:
k=[5,6,7,8]
k.insert(2,66)
k

[5, 6, 66, 7, 8]

In [497]:
import numpy as np
g=np.array([1,3,2,8,4,6])
g

array([1, 3, 2, 8, 4, 6])

In [498]:
np.insert(g,2,77)

array([ 1,  3, 77,  2,  8,  4,  6])

In [499]:
g

array([1, 3, 2, 8, 4, 6])

In [500]:
np.var(g)

5.666666666666667

In [501]:
s=np.mean(g)
s

4.0

In [502]:
t=s-g
t

array([ 3.,  1.,  2., -4.,  0., -2.])

In [503]:
n=t**2
n

array([ 9.,  1.,  4., 16.,  0.,  4.])

In [504]:
sum(n)/len(n)

5.666666666666667

In [505]:
import numpy as np

In [506]:
t=[2000,3000,4000,5000]
t

[2000, 3000, 4000, 5000]

In [507]:
b=[]
for i in t:
    p=i+50
    b.append(p)
    

In [508]:
b

[2050, 3050, 4050, 5050]

In [509]:
m=np.array([2000,3000,4000,5000])
m

array([2000, 3000, 4000, 5000])

In [510]:
m+50

array([2050, 3050, 4050, 5050])

In [511]:
m*18/100

array([360., 540., 720., 900.])

In [512]:
#1 bracket multiarray ke liye hoti hai aur 2 bracket 2d array ke liye hota hai.

In [513]:
s=np.array([[2,1,4],[4,3,6],[9,5,4]])
s

array([[2, 1, 4],
       [4, 3, 6],
       [9, 5, 4]])

In [514]:
s.ndim

2

In [515]:
sum(s)    

array([15,  9, 14])

In [516]:
sum(s)=iska mtlb hai ki isme jo add kiya wo column wise kiya hai na ki row wise

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (2178216475.py, line 1)

In [ ]:
s

In [ ]:
np.sum(s)

In [ ]:
np.sum(s,axis=0)

In [ ]:
#axis=0 means column & axis=1 means rows

In [ ]:
np.sum(s,axis=1)

In [ ]:
s

In [ ]:
np.max(s,axis=0)

In [ ]:
np.min(s,axis=1)

In [ ]:
np.sort(s,axis=1)

In [ ]:
np.sort(s,axis=0)

In [ ]:
# cumsum=cumsum means cumulative sum.

In [ ]:
np.cumsum(s,axis=0)

In [ ]:
######0 axis=column
np.cumsum(s,axis=0)

In [ ]:
s

In [ ]:
np.cumsum(s)

In [ ]:
s

In [ ]:
b=np.array([5,4,3,2,6,7,8,1,2])
b

In [ ]:
b[::-1]

In [ ]:
s[::-1]

In [ ]:
s[::,::-1]

In [ ]:
s

In [ ]:
s[0:2,1:3]

In [ ]:
##############29-5-2024#############

In [ ]:
s

In [ ]:
np.eye(3,3)

In [ ]:
np.zeros((3,3))

In [ ]:
np.ones((3,3))

In [ ]:
np.linalg.det(s)

In [ ]:
np.linalg.inv(s)

In [ ]:
np.linalg.matrix_power(s,2)

In [ ]:
np.linalg.matrix_rank(s)

In [ ]:
s

In [ ]:
np.unique(s)

In [ ]:
s

In [ ]:
h=np.array([[5,6,3],[1,4,5],[5,3,2]])
h

In [ ]:
np.union1d(s,h)

In [ ]:
s

In [ ]:
h

In [ ]:
h2=np.array([[5,6],[1,4],[5,3]])
h2

In [ ]:
np.vstack((h,s))

In [ ]:
np.vstack((h2,s))

In [ ]:
np.hstack((h2,s))

In [ ]:
s

In [ ]:
np.any(s>5)

In [ ]:
np.all(s>5)

In [ ]:
v=np.array([4,5,6])
v

In [ ]:
v2=np.array([4,3,1])
v2

In [ ]:
np.equal(v,v2).all()

In [ ]:
s=np.random.randint(0,10,size=5)
s

In [ ]:
s2=np.random.randint(0,10,size=(3,4))
s2

In [ ]:
h

In [ ]:
np.cumproduct((h))

In [ ]:
h2

In [ ]:
h2.shape

In [ ]:
h2.ndim

In [ ]:
f=np.array([[[4,5,6],[7,8,9],[1,2,3]]])
f

In [ ]:
f.ndim

In [ ]:
f.shape

In [ ]:
h

In [ ]:
h2

In [ ]:
t=np.arange(0,15).reshape(5,3)
t

In [ ]:
h2

In [ ]:
h

In [ ]:
h[1][2]=55
h

In [ ]:
h

In [ ]:
h2

In [ ]:
s2

In [ ]:
t=np.arange(0,30).reshape(2,15)
t

In [ ]:
t.shape

In [ ]:
g=np.hsplit(t,3)
g

In [ ]:
g[0]

In [ ]:
g[1]

In [ ]:
g[2]

In [ ]:
t=np.arange(0,30).reshape(15,2)
t

In [ ]:
u=np.vsplit(t2,3)
u

In [ ]:
###############14-5-2024###################
# pandas=pandas is a inbuilt/predefined/fixed library to manipulate your data ,to analyze your data,calculate your data & any 
# operation of your data set.it is collecting  your data .
# excel &csv diff-csv data :excel file tbhi chalta hai jb excel aapke system ho tb
# hi chalega and csv file kisi me bhi kahi bhi khul jaega


In [ ]:
import pandas as pd
df=pd.read_excel("C:/Users/admin/OneDrive/Desktop/data.xlsx")
df

In [ ]:
df2=pd.read_csv("C:/Users/admin/OneDrive/Desktop/DAA.csv")
df2

In [ ]:
import pymysql as sql
import pandas as pd
db=sql.connect(host="localhost",user='root',password='india123',db='ducat')
df3=pd.read_sql_query("select*from batch46",db)
df3

###### 31/5/2024##################

In [ ]:
#json :json ka data hm server side se uthate hai and wahi se copy path krke apne data me paste kr dete hai.
# json is a unstructured data.JSON KA DATA DICTIONARY FORM ME HOTA HAI.

In [ ]:
import pandas as pd
url=("C:/Users/admin/OneDrive/Desktop/iris.json")
df=pd.read_json(url,orient='column')
df

In [ ]:
url="https://raw.githubusercontent.com/domoritz/maps/master/data/iris.json"
df=pd.read_json(url,orient='column')
df

In [ ]:
import pandas as pd

In [ ]:
df

In [ ]:
#Head is a inbuilt method.to fetch the top 5 records.head bydefault 5 data uthata hai top se.

In [ ]:
df.tail()

In [ ]:
df.head()

In [ ]:
df.head(2)

In [ ]:
df.tail(2)

In [ ]:
import pandas as pd
df2=pd.read_csv("C:/Users/admin/OneDrive/Desktop/DAA.csv")
df2

In [ ]:
df2

In [ ]:
# shape ek inbuilt method hai .jo hmare data ka shape btata hai row and column ka.

In [ ]:
df2.shape

In [ ]:
k=[2,3,4,5,6,7,8,9,12,3,44,67,46,23,14,34,25,89]
len(k)

In [ ]:
# agar he table me column add krna ho tb....

In [ ]:
df2['Tax']=k
df2

In [ ]:
df2

In [ ]:
# ab hm salary he hisab se tax nikalenege.

In [ ]:
df2['Taxsal']=df2['SALARY']*df2['Tax']/100
df2

In [ ]:
# AB HM SALARY ME SE Taxsal MINUS KREGE AUR BASIC SAL NIKALENGE..

In [ ]:
df2['Basicsal']=df2['SALARY']-df2['Taxsal']
df2

In [ ]:
# ab hm chahte hai jo row hai wo column ho jae and jo cplumn hai wo row ho jae
# df.T-t means Transpose matrix[row=column,column=row]

In [ ]:
df2.T

In [ ]:
df2

In [ ]:
# rename of column=agar hme kisi column ka naam change krna ho tb.

In [ ]:
df2

In [ ]:
df2

In [ ]:
df2.rename(columns={'name':'Name','lastname':'Lastname'},inplace=True)
df2

In [ ]:
df2

In [ ]:
# agar hme permanent coulmn changes krna ho tb means fixed name.iske liye use hota hai
# inplace:inplace ek parameter hai jo permanent changes krta hai,mtlb ek bar changes ho gya to wo phir waise hi rhega

In [ ]:
df2.drop(['Tax','AGE'],axis=1)

In [ ]:
# hmesa yaad rakhna numpy me axis-0=column,axis-1=row / pandas me axis-0=row, axis-1=column hota hai

In [ ]:
df2

In [ ]:
# ab hm salary ke hisab se rank decide krege.
# rank hmesa ascending order ke behalf pr bydefault rank nikalta hai.

In [ ]:
df2.sort_values("NAME")

In [ ]:
df2.sort_values("NAME",ascending=False)

In [ ]:
# rank naam ka column bydefault ascending order ke behalf pr rank nikalta hai

In [ ]:
df2['rank']=df2['SALARY'].rank()
df2

In [ ]:
df2['rank']=df2['SALARY'].rank(ascending=False)
df2

In [ ]:
# import numpy as np
# import pandas as pd
df2['rank']=df2['SALARY'].rank(ascending=False).astype("int")
df2

In [ ]:
df2.sort_values('SALARY',ascending=False)

In [ ]:
df2.loc[df2['NAME']=='ram',['SALARY']]=67857
df2

In [ ]:
##########################11/06/2024#####################

In [ ]:
df2

In [ ]:
df2['DenseRank']=df2['SALARY'].rank(method='dense',ascending=False).astype('int')
df2

In [ ]:
df2.sort_values('SALARY',ascending=False)

In [ ]:
df2.sort_values('SALARY',ascending=False).head(1)

In [ ]:
df2.sort_values('SALARY',ascending=False).tail(1)

In [ ]:
df2.nlargest(3,'SALARY')

In [ ]:
df2.nsmallest(3,'SALARY')

In [ ]:
df2

In [ ]:
k=df2['NAME']
k2=list(k)
k2

In [ ]:
r=[]
for i in k2:
    n=i.title()
    r.append(n)

In [ ]:
r

In [ ]:
df2['NAME']=r
r

In [ ]:
df2

In [ ]:
df2.drop(['AGE','CONTACT'],axis=1)

In [ ]:
df2

In [ ]:
df2.drop([2,5,10,6],axis=0)

In [517]:
df2.drop([2,5,10,6],axis=0)

ID      NAME LASTNAME  SALARY      CONTACT  AGE  Tax     Taxsal  \
0   1620     Nidhi   pandey   23453  56983473986   45    2     469.06   
1   1621     Neelu   sharma   12000    986776476   76    3     360.00   
3   1623       Ram    rahim   67857        34564   32    5     232.75   
4   1624      Ravi      rai    4565       445653   34    6     273.90   
7   1627      Amir   sharma  546543       678757   44    9   49188.87   
8   1628     Kajal    shama    5445        67857   45   12     653.40   
9   1629  Karishma   kumari   76654     86675645   76    3    2299.62   
11  1631    Saumya   tiwari  344554     89876565   34   67  230851.18   
12  1632     Pooja    singh     345    568655664   34   46     158.70   
13  1633    Sheela    patel   64563      5766556   76   23   14849.49   
14  1634    Diksha    singh  455665  47676544343   65   14   63793.10   
15  1635     Neelu    patel    4554      3445655   54   34    1548.36   
16  1636      Akku   pandey  456654     34455645   32   25  114163.50   
17  1637   Purnima   purvaj    4556     45565645   34   89    4054.84   

     Basicsal  rank  DenseRank  
0    22983.94    12         12  
1    11640.00    13         13  
3     4422.25     6          6  
4     4291.10    15         15  
7   497354.13     1          1  
8     4791.60    14         14  
9    74354.38     5          5  
11  113702.82     4          4  
12     186.30    18         18  
13   49713.51     7          7  
14  391871.90     3          3  
15    3005.64    17         17  
16  342490.50     2          2  
17     501.16    16         16

In [518]:
df2[['SALARY','Taxsal']].max()

SALARY    546543.00
Taxsal    230851.18
dtype: float64

In [519]:
df2[['SALARY','Taxsal']].sum()

SALARY    2223285.00
Taxsal     505543.23
dtype: float64

In [520]:
df=pd.read_excel("C:/Users/admin/OneDrive/Desktop/subject.xlsx")
df

Name  hindi  eng  math   art  sci
0      ravi     34   67     89   77   34
1    sachin     35   70     94   80   40
2     seema     36   73     99   83   46
3       ram     37   76     46   86   52
4     nisha     38   79     48   89   58
5     nupur     39   82     50   92   64
6   radhika     40   85     52   95   70
7      rani     41   88     54   98   76
8     richa     42   91     56  101   82
9    sudhir     43   94     58  104   88
10    sumit     44   97     60  107   94
11   shikha     45  100     62  110  100

In [521]:
# MAP:MAP,KISI BHI TABLE KE ANDAR KISI BHI COLUMN KE ANDAR AGGREGATION KRTA HAI.


In [522]:
t=df['hindi']
t2=list(t)
t2

[34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]

In [523]:
e=df['eng']
e2=list(e)
e2

[67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100]

In [524]:
b=list(map(lambda x,y:x+y,t2,e2))
b       

[101, 105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145]

In [525]:
# map naam ka function list ke andar column ke andar max min nikalne ke kaam aata hai
# ex:2list ko jodne ka kaam krta hai.

In [526]:
# apply:apply will be work on row wise sum


In [527]:
g=df[['hindi','eng','art','sci']].apply(sum,axis=1)
g

0     212
1     225
2     238
3     251
4     264
5     277
6     290
7     303
8     316
9     329
10    342
11    355
dtype: int64

In [528]:
df['Total']=g
g

0     212
1     225
2     238
3     251
4     264
5     277
6     290
7     303
8     316
9     329
10    342
11    355
dtype: int64

In [529]:
df

Name  hindi  eng  math   art  sci  Total
0      ravi     34   67     89   77   34    212
1    sachin     35   70     94   80   40    225
2     seema     36   73     99   83   46    238
3       ram     37   76     46   86   52    251
4     nisha     38   79     48   89   58    264
5     nupur     39   82     50   92   64    277
6   radhika     40   85     52   95   70    290
7      rani     41   88     54   98   76    303
8     richa     42   91     56  101   82    316
9    sudhir     43   94     58  104   88    329
10    sumit     44   97     60  107   94    342
11   shikha     45  100     62  110  100    355

In [530]:
df['percent']=df['Total']/5
df

Name  hindi  eng  math   art  sci  Total  percent
0      ravi     34   67     89   77   34    212     42.4
1    sachin     35   70     94   80   40    225     45.0
2     seema     36   73     99   83   46    238     47.6
3       ram     37   76     46   86   52    251     50.2
4     nisha     38   79     48   89   58    264     52.8
5     nupur     39   82     50   92   64    277     55.4
6   radhika     40   85     52   95   70    290     58.0
7      rani     41   88     54   98   76    303     60.6
8     richa     42   91     56  101   82    316     63.2
9    sudhir     43   94     58  104   88    329     65.8
10    sumit     44   97     60  107   94    342     68.4
11   shikha     45  100     62  110  100    355     71.0

In [531]:
def per(x):
    if x>80 and x<100:
        return 'A'
    elif(x>60 and x<80):
        return 'B'
    elif(x>50 and x<60):
        return 'C'
    else:
        return 'Fail'

In [532]:
df['Grade']=df['percent'].apply(per)
df

Name  hindi  eng  math   art  sci  Total  percent Grade
0      ravi     34   67     89   77   34    212     42.4  Fail
1    sachin     35   70     94   80   40    225     45.0  Fail
2     seema     36   73     99   83   46    238     47.6  Fail
3       ram     37   76     46   86   52    251     50.2     C
4     nisha     38   79     48   89   58    264     52.8     C
5     nupur     39   82     50   92   64    277     55.4     C
6   radhika     40   85     52   95   70    290     58.0     C
7      rani     41   88     54   98   76    303     60.6     B
8     richa     42   91     56  101   82    316     63.2     B
9    sudhir     43   94     58  104   88    329     65.8     B
10    sumit     44   97     60  107   94    342     68.4     B
11   shikha     45  100     62  110  100    355     71.0     B

In [533]:
df

Name  hindi  eng  math   art  sci  Total  percent Grade
0      ravi     34   67     89   77   34    212     42.4  Fail
1    sachin     35   70     94   80   40    225     45.0  Fail
2     seema     36   73     99   83   46    238     47.6  Fail
3       ram     37   76     46   86   52    251     50.2     C
4     nisha     38   79     48   89   58    264     52.8     C
5     nupur     39   82     50   92   64    277     55.4     C
6   radhika     40   85     52   95   70    290     58.0     C
7      rani     41   88     54   98   76    303     60.6     B
8     richa     42   91     56  101   82    316     63.2     B
9    sudhir     43   94     58  104   88    329     65.8     B
10    sumit     44   97     60  107   94    342     68.4     B
11   shikha     45  100     62  110  100    355     71.0     B

In [534]:
t=df.select_dtypes(['int','float'])
t

hindi  eng  math   art  sci  Total  percent
0      34   67     89   77   34    212     42.4
1      35   70     94   80   40    225     45.0
2      36   73     99   83   46    238     47.6
3      37   76     46   86   52    251     50.2
4      38   79     48   89   58    264     52.8
5      39   82     50   92   64    277     55.4
6      40   85     52   95   70    290     58.0
7      41   88     54   98   76    303     60.6
8      42   91     56  101   82    316     63.2
9      43   94     58  104   88    329     65.8
10     44   97     60  107   94    342     68.4
11     45  100     62  110  100    355     71.0

In [535]:
# map:map hmesa column pr apply hota hai. 
# apply:apply row-column  dono pr apply hota hai.
# applyall:applyall pure data pr work  krta hai

In [536]:
r=t.applymap(lambda x:x+10)
r

C:\Users\admin\AppData\Local\Temp\ipykernel_8784\2463533730.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  r=t.applymap(lambda x:x+10)


hindi  eng  math   art  sci  Total  percent
0      44   77     99   87   44    222     52.4
1      45   80    104   90   50    235     55.0
2      46   83    109   93   56    248     57.6
3      47   86     56   96   62    261     60.2
4      48   89     58   99   68    274     62.8
5      49   92     60  102   74    287     65.4
6      50   95     62  105   80    300     68.0
7      51   98     64  108   86    313     70.6
8      52  101     66  111   92    326     73.2
9      53  104     68  114   98    339     75.8
10     54  107     70  117  104    352     78.4
11     55  110     72  120  110    365     81.0

In [537]:
df

Name  hindi  eng  math   art  sci  Total  percent Grade
0      ravi     34   67     89   77   34    212     42.4  Fail
1    sachin     35   70     94   80   40    225     45.0  Fail
2     seema     36   73     99   83   46    238     47.6  Fail
3       ram     37   76     46   86   52    251     50.2     C
4     nisha     38   79     48   89   58    264     52.8     C
5     nupur     39   82     50   92   64    277     55.4     C
6   radhika     40   85     52   95   70    290     58.0     C
7      rani     41   88     54   98   76    303     60.6     B
8     richa     42   91     56  101   82    316     63.2     B
9    sudhir     43   94     58  104   88    329     65.8     B
10    sumit     44   97     60  107   94    342     68.4     B
11   shikha     45  100     62  110  100    355     71.0     B

In [538]:
# iloc:iloc means integer location
# Loc:loc means label location
# YE DAAFRAME ME SLICING KA KAAM KRTE HAI

In [539]:
df.iloc[0:4]

Name  hindi  eng  math   art  sci  Total  percent Grade
0    ravi     34   67     89   77   34    212     42.4  Fail
1  sachin     35   70     94   80   40    225     45.0  Fail
2   seema     36   73     99   83   46    238     47.6  Fail
3     ram     37   76     46   86   52    251     50.2     C

In [540]:
df.iloc[0:4,2:5]

eng  math   art
0   67     89   77
1   70     94   80
2   73     99   83
3   76     46   86

In [541]:
df.iloc[3:6,2:8]

eng  math   art  sci  Total  percent
3   76     46   86   52    251     50.2
4   79     48   89   58    264     52.8
5   82     50   92   64    277     55.4

In [542]:
# LOC:LABEL LOCATION KA MTLB HOTA HAI KI AAPKA DATA JO SLICE HOGA WO INTEGER PE NHI LABEL PR HOGA MTLB TEXT TYPE KE DATA PR HOGA

In [543]:
df2

ID      NAME LASTNAME  SALARY      CONTACT  AGE  Tax     Taxsal  \
0   1620     Nidhi   pandey   23453  56983473986   45    2     469.06   
1   1621     Neelu   sharma   12000    986776476   76    3     360.00   
2   1622    Sheela    dubey   45655   4567545445   46    4    1826.20   
3   1623       Ram    rahim   67857        34564   32    5     232.75   
4   1624      Ravi      rai    4565       445653   34    6     273.90   
5   1625     Nancy   sonkar   43334    345656554   34    7    3033.38   
6   1626     Farah      rai   32344     45566778   65    8    2587.52   
7   1627      Amir   sharma  546543       678757   44    9   49188.87   
8   1628     Kajal    shama    5445        67857   45   12     653.40   
9   1629  Karishma   kumari   76654     86675645   76    3    2299.62   
10  1630    Garima    singh   34544   5686757475   22   44   15199.36   
11  1631    Saumya   tiwari  344554     89876565   34   67  230851.18   
12  1632     Pooja    singh     345    568655664   34   46     158.70   
13  1633    Sheela    patel   64563      5766556   76   23   14849.49   
14  1634    Diksha    singh  455665  47676544343   65   14   63793.10   
15  1635     Neelu    patel    4554      3445655   54   34    1548.36   
16  1636      Akku   pandey  456654     34455645   32   25  114163.50   
17  1637   Purnima   purvaj    4556     45565645   34   89    4054.84   

     Basicsal  rank  DenseRank  
0    22983.94    12         12  
1    11640.00    13         13  
2    43828.80     8          8  
3     4422.25     6          6  
4     4291.10    15         15  
5    40300.62     9          9  
6    29756.48    11         11  
7   497354.13     1          1  
8     4791.60    14         14  
9    74354.38     5          5  
10   19344.64    10         10  
11  113702.82     4          4  
12     186.30    18         18  
13   49713.51     7          7  
14  391871.90     3          3  
15    3005.64    17         17  
16  342490.50     2          2  
17     501.16    16         16

In [544]:
r=df2.set_index('NAME')
r

ID LASTNAME  SALARY      CONTACT  AGE  Tax     Taxsal   Basicsal  \
NAME                                                                           
Nidhi     1620   pandey   23453  56983473986   45    2     469.06   22983.94   
Neelu     1621   sharma   12000    986776476   76    3     360.00   11640.00   
Sheela    1622    dubey   45655   4567545445   46    4    1826.20   43828.80   
Ram       1623    rahim   67857        34564   32    5     232.75    4422.25   
Ravi      1624      rai    4565       445653   34    6     273.90    4291.10   
Nancy     1625   sonkar   43334    345656554   34    7    3033.38   40300.62   
Farah     1626      rai   32344     45566778   65    8    2587.52   29756.48   
Amir      1627   sharma  546543       678757   44    9   49188.87  497354.13   
Kajal     1628    shama    5445        67857   45   12     653.40    4791.60   
Karishma  1629   kumari   76654     86675645   76    3    2299.62   74354.38   
Garima    1630    singh   34544   5686757475   22   44   15199.36   19344.64   
Saumya    1631   tiwari  344554     89876565   34   67  230851.18  113702.82   
Pooja     1632    singh     345    568655664   34   46     158.70     186.30   
Sheela    1633    patel   64563      5766556   76   23   14849.49   49713.51   
Diksha    1634    singh  455665  47676544343   65   14   63793.10  391871.90   
Neelu     1635    patel    4554      3445655   54   34    1548.36    3005.64   
Akku      1636   pandey  456654     34455645   32   25  114163.50  342490.50   
Purnima   1637   purvaj    4556     45565645   34   89    4054.84     501.16   

          rank  DenseRank  
NAME                       
Nidhi       12         12  
Neelu       13         13  
Sheela       8          8  
Ram          6          6  
Ravi        15         15  
Nancy        9          9  
Farah       11         11  
Amir         1          1  
Kajal       14         14  
Karishma     5          5  
Garima      10         10  
Saumya       4          4  
Pooja       18         18  
Sheela       7          7  
Diksha       3          3  
Neelu       17         17  
Akku         2          2  
Purnima     16         16

In [545]:
r.loc['nidhi':'ravi','SALARY':'rank']

KeyError: 'nidhi'

In [ ]:
# HMNE YAHA INDEX KO TEXT BNA DIYA

In [ ]:
# sample:sample yaha randomly hota hai.isko hm jitni bar hi run krege wo update hota rhega

In [ ]:
df.sample(2)

In [ ]:
df2

In [ ]:
df2.drop_duplicates()

In [ ]:
df2[df2.duplicated(['LASTNAME'])]

In [ ]:
df2[df2.duplicated(['LASTNAME'],keep='last')]

In [ ]:
df2

In [ ]:
df2.sort_values(['SALARY','NAME'],ascending=[False,True])

In [ ]:
# ab hm jiski salary 60000 se jyda ho wo log aa jae

In [ ]:
df2[(df2['SALARY']>5000)&(df2['SALARY']<50000)]

In [ ]:
df2[(df2['SALARY']>5000)|(df2['SALARY']<50000)]

In [ ]:
df2[(df2['NAME']=='Ravi')&(df2['LASTNAME']=='rai')]

In [ ]:
df2[(df2['NAME']=='Ravi')|(df2['LASTNAME']=='pandey')]

In [ ]:
df2

In [ ]:
df2[df2['NAME'].isin(['nidhi','garima','ravi'])]

In [ ]:
df2

In [ ]:
# ############14/6/2024###########################

In [ ]:
df2

In [ ]:
df2[~df2['NAME'].isin(['nidhi','garima','ravi'])]
df2

In [ ]:
df2.rename(columns={'SALARY':'Amount','Basicsal':'Totalsal'})
df2

In [ ]:
df2

In [ ]:
# SERIES METHOD:SERIES REPRESENT YOUR DATA INTO  1-D ARRARY.SERIES WILL BE WORK ON INDEX.

In [ ]:
import numpy as np

In [ ]:
s=np.array([5,6,7,8,1])
s

In [ ]:
s2=np.array([2,3,4,5,7])
s2

In [ ]:
s+s2

In [ ]:
import pandas as pd

In [ ]:
t=pd.Series([4,5,6,2,1],index=['A','B','C','D','E'])
t

In [ ]:
t.ndim

In [ ]:
t2=pd.Series([6,7,8,9,4],index=['x','y','A','N','E'])
t2

In [ ]:
t+t2

In [ ]:
df2

In [ ]:
g=df2['NAME']
g

In [ ]:
g=df2['NAME']
g2=list(g)
g2

In [ ]:
len(g2)

In [ ]:
r=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R']
len(r)

In [ ]:
m=pd.Series(g2,index=r)
m

In [ ]:
df2

In [ ]:
df2['Index']=r

In [ ]:
df2

In [ ]:
df2.set_index('Index')

In [ ]:
df2

In [ ]:
# GROUP BY:GROUP BY MEANS JB HM KISI DATA KA GROUP BY KRTE HAI TO WO CATEGORIZED WISE HO JATA HAI

In [ ]:
import pandas as pd

In [ ]:
ipl_data = {'Team':['Riders','Riders','Devils','Devils','kings','kings','kings','kings','Riders','Royals','Royals','Riders'],
            'Rank':[1,2,2,3,3,4,1,1,2,4,1,2],
            'Year':[2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
            'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df=pd.DataFrame(ipl_data)
df

In [ ]:
t=df.groupby(['Year'])
t

In [ ]:
for i,j in t:
    print(i)
    print(j)

In [ ]:
t2=df.groupby(['Team'])
t2

In [ ]:
for i,j in t2:
    print(i)
    print(j)

In [ ]:
t['Team'].value_counts()

In [ ]:
ipl_data = {'Team':['Riders','Riders','Devils','Devils','kings','kings','kings','kings','Riders','Royals','Royals','Riders'],
            'Rank':[1,2,2,3,3,4,1,1,2,4,1,2],
            'Year':[2014,2014,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
            'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df=pd.DataFrame(ipl_data)
df

In [ ]:
t2=df.groupby(['Year'])
t2

In [ ]:
t2['Team'].value_counts()

In [ ]:
t=df.groupby(['Team'])
t

In [ ]:
for i, j in t:
    print(i)
    print(j)

In [ ]:
t['Points'].sum()

In [ ]:
p=t['Points'].sum()
p

In [ ]:
type(p)

In [ ]:
df=pd.DataFrame(p)
df

In [ ]:
df.sort_values('Points',ascending=False)


In [ ]:
df.sort_values('Points',ascending=False).head(1)

In [ ]:
df[df.Points==df['Points'].max()]
df

In [ ]:
s=df.groupby(['Year','Team'])
s

In [ ]:
for i ,j in s:
    print(i)
    print(j)
    

In [ ]:
s=df.groupby(['Year'])
s

In [ ]:
r=s[['Team','Points']].sum()
r

In [ ]:
df.groupby(['Year','Team',])[['Points']].sum()

In [ ]:
df

In [ ]:
df[df.Points==df['Points'].max()]

In [ ]:
# PIVOT TABLE:SUMMARIZATION OF OVERALL DATA WITH AGGREGATION FUNCTION IS CALLED PIVOT TABLE.

In [ ]:
df.pivot_table(index='Team')               

In [ ]:
df[['Points','Team']].pivot_table(index='Team')  

In [ ]:
df[['Points','Year']].pivot_table(index='Year',aggfunc="sum")  

In [ ]:
df

In [ ]:
df2

In [ ]:
df

In [ ]:
df.pivot_table(index='Team',columns='Year',aggfunc='max',fill_value=0)

In [ ]:
df.pivot_table(index='Team',columns='Year',aggfunc='count',fill_value=0)
df.pivot_table(index='Team',columns='Year',aggfunc='max',fill_value=0)
df.pivot_table(index='Team',columns='Year',aggfunc='sum',fill_value=0,margins=True)

In [ ]:
concatenate
join

t=df.iloc[6:,0:]
t2=df.iloc[0:6,0]

p=df.concat([g,g2],axis=1)
p

# joins in pandas:pandas
left join right join inner join full join